@startuml C2 Containers Diagram
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!include FONTAWESOME/android.puml
!include FONTAWESOME/apple.puml
!include FONTAWESOME/autoprefixer.puml
!include FONTAWESOME/aws.puml
!include FONTAWESOME/firefox_browser.puml
!include FONTAWESOME/piggy_bank.puml
!include FONTAWESOME/shipping_fast.puml
!include FONTAWESOME/users.puml

Boundary($alias="system_boundary", "System Boundary"){
    Container_Boundary($alias="frontend_boundary", "Frontend Boundary") {
        System($alias="webapp", $label="Web application", $descr="Browsers", $sprite="firefox_browser")
        System($alias="android", $label="Android application", $descr="Android devices", $sprite="android")
        System($alias="ios", $label="iOS Application", $descr="Apple-built devices", $sprite="apple")
    }
    Container_Boundary($alias="backend_boundary", "Backend Boundary") {
        System($alias="api", $label="Azteczon API", $descr="REST API layer", $sprite="autoprefixer")
        System($alias="aws", $label="Serverless Architecture", $descr="AWS-based serverless architecture", $sprite="aws")
        BiRel("api", "aws", "HTTPS")
    }

    BiRel_R("frontend_boundary", "api", "HTTPS")
}
Person_Ext("users", "Users", "Users of the e-commerce system", $sprite="users")
System_Ext("banking", "Banking System", "Banks & Other Financial Institutions", $sprite="piggy_bank")
System_Ext("email", "e-mail System", "Vendor e-mail system", $sprite="mail_bulk")
System_Ext("ship", "Shipping Vendors", "Independent People or Companies", $sprite="shipping_fast")

'External relationships
BiRel_D("users", "frontend_boundary", "HTTP(S)/WebSockets/GraphQL/...")
BiRel("aws", "banking", "")
BiRel("aws", "email", "")
BiRel("aws", "ship", "")

@enduml